notify() {
    notify-send -t 3000 "march wallpaper" "$1" 2>/dev/null || printf '%s\n' "$1" >&2
}

notify_applied() {
    local image="$1"
    local accent="${2:-}"
    local message="Applied $(basename "$image")"

    if [[ -n "$accent" ]]; then
        message="$message\nAccent $accent"
    fi

    notify-send -t 3000 -i "$image" "march wallpaper" "$message" 2>/dev/null || printf '%b\n' "$message" >&2
}

current_image() {
    [[ -f "$current_wallpaper" ]] || return 1
    sed -n '1p' "$current_wallpaper"
}

ensure_dirs() {
    mkdir -p "$state_dir" "$generated_dir" "$repo_dir/wallpapers"

    if [[ ! -f "$rofi_colors" ]]; then
        printf '* {}\n' > "$rofi_colors"
    fi

    if [[ ! -f "$kitty_colors" ]]; then
        printf '# Generated by scripts/wallpaper.sh\n' > "$kitty_colors"
    fi
}

list_wallpapers() {
    IFS=':' read -r -a dirs <<< "$wallpaper_dirs"

    for dir in "${dirs[@]}"; do
        [[ -d "$dir" ]] || continue
        find "$dir" -type f \( \
            -iname '*.jpg' -o \
            -iname '*.jpeg' -o \
            -iname '*.png' -o \
            -iname '*.webp' -o \
            -iname '*.avif' -o \
            -iname '*.bmp' -o \
            -iname '*.gif' \
        \)
    done | sort -u
}

pick_wallpaper() {
    local selected

    selected="$(
        list_wallpapers | rofi -dmenu \
            -config "$palette_config" \
            -p "wallpaper" \
            -mesg "Local wallpapers from ./wallpapers and ~/Pictures/Wallpapers"
    )"

    [[ -n "$selected" ]] || exit 0
    apply_wallpaper "$selected"
}

random_wallpaper() {
    local selected

    selected="$(list_wallpapers | shuf -n 1)"
    if [[ -z "$selected" ]]; then
        notify "No local wallpapers found"
        exit 1
    fi

    apply_wallpaper "$selected"
}

show_current_wallpaper() {
    local image accent

    image="$(current_image || true)"
    if [[ -z "$image" || ! -f "$image" ]]; then
        notify "No current wallpaper"
        exit 1
    fi

    accent=""
    if [[ -f "$march_colors_json" ]] && command -v jq >/dev/null 2>&1; then
        accent="$(jq -r '.accent // empty' "$march_colors_json" 2>/dev/null || true)"
    fi

    notify_applied "$image" "$accent"
}

open_current_wallpaper_folder() {
    local image

    image="$(current_image || true)"
    if [[ -z "$image" || ! -f "$image" ]]; then
        notify "No current wallpaper"
        exit 1
    fi

    xdg-open "$(dirname "$image")" >/tmp/march-wallpaper-folder.log 2>&1 &
}

remember_wallpaper() {
    local image="$1"

    [[ -n "$image" && -f "$image" ]] || return 0
    {
        printf '%s\n' "$image"
        if [[ -f "$wallpaper_history" ]]; then
            grep -Fxv -- "$image" "$wallpaper_history" || true
        fi
    } | sed -n '1,20p' > "$wallpaper_history.tmp"
    mv "$wallpaper_history.tmp" "$wallpaper_history"
}

previous_wallpaper() {
    local previous current

    previous="$(sed -n '1p' "$wallpaper_history" 2>/dev/null || true)"
    if [[ -z "$previous" || ! -f "$previous" ]]; then
        notify "No previous wallpaper"
        exit 1
    fi

    current="$(current_image || true)"
    if [[ -n "$current" && -f "$current" && "$current" != "$previous" ]]; then
        {
            printf '%s\n' "$current"
            grep -Fxv -- "$previous" "$wallpaper_history" 2>/dev/null | grep -Fxv -- "$current" || true
        } | sed '/^$/d' | sed -n '1,20p' > "$wallpaper_history.tmp"
        mv "$wallpaper_history.tmp" "$wallpaper_history"
    else
        sed '1d' "$wallpaper_history" > "$wallpaper_history.tmp"
        mv "$wallpaper_history.tmp" "$wallpaper_history"
    fi

    apply_wallpaper "$previous" --no-history
}

apply_wallpaper() {
    local image="$1"
    local mode="${2:-}"

    if [[ ! -f "$image" ]]; then
        notify "Wallpaper not found: $image"
        exit 1
    fi

    ensure_dirs

    local previous=""
    previous="$(current_image || true)"
    if [[ "$mode" != "--no-history" && -n "$previous" && "$previous" != "$image" ]]; then
        remember_wallpaper "$previous"
    fi

    printf '%s\n' "$image" > "$current_wallpaper"

    if command -v awww >/dev/null 2>&1; then
        awww img "$image" \
            --resize crop \
            --filter Lanczos3 \
            --transition-type grow \
            --transition-duration 0.8 \
            --transition-pos center \
            >/dev/null 2>&1 || true
    fi

    generate_palette "$image"
    local accent=""
    if [[ -f "$march_colors_json" ]] && command -v jq >/dev/null 2>&1; then
        accent="$(jq -r '.accent // empty' "$march_colors_json" 2>/dev/null || true)"
    fi
    notify_applied "$image" "$accent"
}
