theme_picker() {
    local selected

    selected="$(
        printf '%s\n' \
            "@ theme dynamic from wallpaper" \
            "@ theme fallback march glass" \
            "@ theme regenerate current" \
            "@ theme status" |
            rofi -dmenu \
                -config "$palette_config" \
                -p "theme" \
                -mesg "Dynamic uses matugen from current wallpaper. Fallback uses fixed march glass."
    )" || exit 0

    case "$selected" in
        "@ theme dynamic from wallpaper" | "@ theme regenerate current")
            enable_dynamic_theme
            ;;
        "@ theme fallback march glass")
            enable_fallback_theme
            ;;
        "@ theme status")
            theme_status
            ;;
    esac
}

enable_dynamic_theme() {
    local image

    image="$(current_image || true)"
    if [[ -z "$image" || ! -f "$image" ]]; then
        notify "No current wallpaper to generate from"
        exit 1
    fi

    printf 'dynamic\n' > "$theme_mode"
    generate_palette "$image"
    notify "Dynamic theme generated from $(basename "$image")"
}

enable_fallback_theme() {
    printf 'fallback\n' > "$theme_mode"
    printf '{}\n' > "$march_colors_json"
    printf '* {}\n' > "$rofi_colors"
    printf '# Generated by scripts/wallpaper.sh\n' > "$kitty_colors"
    notify "Using fallback march glass theme"
}

theme_status() {
    local mode accent image

    mode="$(sed -n '1p' "$theme_mode" 2>/dev/null || printf 'dynamic')"
    image="$(current_image || true)"
    accent=""
    if [[ -f "$march_colors_json" ]] && command -v jq >/dev/null 2>&1; then
        accent="$(jq -r '.accent // empty' "$march_colors_json" 2>/dev/null || true)"
    fi

    notify "Mode: $mode
Wallpaper: ${image:+$(basename "$image")}
Accent: ${accent:-fallback}"
}

generate_palette() {
    local image="$1"
    local matugen_tmp="$generated_dir/matugen.json.tmp"

    if ! command -v matugen >/dev/null 2>&1; then
        notify "Wallpaper applied. matugen is not installed, skipped colors."
        return 0
    fi

    if ! matugen image "$image" \
        --mode dark \
        --type scheme-tonal-spot \
        --source-color-index 0 \
        --json hex \
        > "$matugen_tmp" \
        2> "$generated_dir/matugen.log"; then
        rm -f "$matugen_tmp"
        notify "Wallpaper applied. matugen failed, skipped colors."
    else
        mv "$matugen_tmp" "$matugen_json"
        rm -f "$generated_dir/matugen.log"
        write_generated_palette
    fi
}

hex_to_rofi_rgba() {
    local hex="${1#"#"}"
    local alpha="$2"

    printf 'rgba(%d, %d, %d, %s%%)' \
        "0x${hex:0:2}" \
        "0x${hex:2:2}" \
        "0x${hex:4:2}" \
        "$alpha"
}

hex_to_qml_argb() {
    local hex="${1#"#"}"
    local alpha="$2"

    printf '#%s%s' "$alpha" "$hex"
}

write_generated_palette() {
    if [[ ! -f "$matugen_json" ]]; then
        notify "No matugen palette found yet"
        return 1
    fi

    if ! command -v jq >/dev/null 2>&1; then
        notify "Wallpaper applied. jq is not installed, skipped generated theme."
        return 0
    fi

    local bg bg_soft text text_muted text_dim accent accent2 accent3 error
    bg="$(jq -r '.colors.background.dark.color // "#0B0D12"' "$matugen_json")"
    bg_soft="$(jq -r '.colors.surface_container.dark.color // .colors.surface.dark.color // "#11141B"' "$matugen_json")"
    text="$(jq -r '.colors.on_surface.dark.color // "#F2F4F8"' "$matugen_json")"
    text_muted="$(jq -r '.colors.on_surface_variant.dark.color // "#A8B0C0"' "$matugen_json")"
    text_dim="$(jq -r '.colors.outline.dark.color // "#6F7787"' "$matugen_json")"
    accent="$(jq -r '.colors.primary.dark.color // "#8AADF4"' "$matugen_json")"
    accent2="$(jq -r '.colors.secondary.dark.color // "#C6A0F6"' "$matugen_json")"
    accent3="$(jq -r '.colors.tertiary.dark.color // "#91D7E3"' "$matugen_json")"
    error="$(jq -r '.colors.error.dark.color // "#ED8796"' "$matugen_json")"

    jq -n \
        --arg bg "$bg" \
        --arg bgSoft "$bg_soft" \
        --arg surface "$(hex_to_qml_argb "$bg_soft" "85")" \
        --arg surfaceStrong "$(hex_to_qml_argb "$bg_soft" "ad")" \
        --arg glassBg "$(hex_to_qml_argb "$bg" "75")" \
        --arg glassBorder "#24ffffff" \
        --arg glassHighlight "#38ffffff" \
        --arg glassShadow "#59000000" \
        --arg text "$text" \
        --arg textMuted "$text_muted" \
        --arg textDim "$text_dim" \
        --arg accent "$accent" \
        --arg accent2 "$accent2" \
        --arg accent3 "$accent3" \
        --arg success "$accent3" \
        --arg warning "$accent2" \
        --arg error "$error" \
        --arg barBg "$(hex_to_qml_argb "$bg" "94")" \
        --arg barBorder "#21ffffff" \
        --arg barActive "$(hex_to_qml_argb "$accent" "66")" \
        --arg barHover "#1affffff" \
        '{
            bg: $bg,
            bgSoft: $bgSoft,
            surface: $surface,
            surfaceStrong: $surfaceStrong,
            glassBg: $glassBg,
            glassBorder: $glassBorder,
            glassHighlight: $glassHighlight,
            glassShadow: $glassShadow,
            text: $text,
            textMuted: $textMuted,
            textDim: $textDim,
            accent: $accent,
            accent2: $accent2,
            accent3: $accent3,
            success: $success,
            warning: $warning,
            error: $error,
            barBg: $barBg,
            barBorder: $barBorder,
            barActive: $barActive,
            barHover: $barHover
        }' > "$march_colors_json"

    cat > "$rofi_colors" <<EOF
* {
    bg: $bg;
    surface: $(hex_to_rofi_rgba "$accent" 32);
    glass-bg: $(hex_to_rofi_rgba "$bg" 58);
    glass-border: rgba(255, 255, 255, 13%);
    glass-highlight: rgba(255, 255, 255, 18%);
    text: $text;
    text-muted: $text_muted;
    text-dim: $text_dim;
    accent: $accent;
    accent-2: $accent2;
}

window {
    background-color: $(hex_to_rofi_rgba "$bg" 78);
}

inputbar {
    background-color: rgba(255, 255, 255, 8%);
}

element selected {
    background-color: $(hex_to_rofi_rgba "$accent" 36);
}

button selected {
    background-color: $(hex_to_rofi_rgba "$accent2" 20);
}
EOF

    cat > "$kitty_colors" <<EOF
# Generated by scripts/wallpaper.sh

foreground $text
background $bg
selection_foreground $bg
selection_background $accent

cursor $accent
cursor_text_color $bg

url_color $accent3
active_border_color $accent
inactive_border_color $text_dim
bell_border_color $accent2
visual_bell_color $accent2

active_tab_foreground $bg
active_tab_background $accent
inactive_tab_foreground $text_muted
inactive_tab_background $bg_soft
tab_bar_background $bg

color0 $bg_soft
color1 $error
color2 #A6DA95
color3 #EED49F
color4 $accent
color5 $accent2
color6 $accent3
color7 $text

color8 $text_dim
color9 $error
color10 #A6DA95
color11 #EED49F
color12 $accent
color13 $accent2
color14 $accent3
color15 #FFFFFF
EOF
}
