# march Hyprland config layer

general {
    gaps_in = 6
    gaps_out = 12
    border_size = 1
}

decoration {
    rounding = 16

    blur {
        enabled = true
        size = 8
        passes = 3
    }
}

animations {
    enabled = true
}
