#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
generated_kitty_theme="$repo_dir/themes/generated/kitty-colors.conf"

mkdir -p "$(dirname "$generated_kitty_theme")"
if [[ ! -f "$generated_kitty_theme" ]]; then
    printf '# Generated by scripts/wallpaper.sh\n' > "$generated_kitty_theme"
fi

exec kitty --config "$repo_dir/kitty/kitty.conf"
