#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
state_dir="$repo_dir/state"
generated_dir="$repo_dir/themes/generated"
palette_config="$repo_dir/rofi/command-palette.rasi"
wallpaper_dirs="${MARCH_WALLPAPER_DIRS:-$repo_dir/wallpapers:$HOME/Pictures/Wallpapers}"
online_wallpaper_dir="${MARCH_ONLINE_WALLPAPER_DIR:-$HOME/Pictures/Wallpapers}"
current_wallpaper="$state_dir/current-wallpaper"
wallpaper_history="$state_dir/wallpaper-history"
theme_mode="$state_dir/theme-mode"
matugen_json="$generated_dir/matugen.json"
march_colors_json="$generated_dir/march-colors.json"
rofi_colors="$generated_dir/rofi-colors.rasi"
kitty_colors="$generated_dir/kitty-colors.conf"

usage() {
    cat <<'EOF'
Usage:
  wallpaper.sh --pick
  wallpaper.sh --random
  wallpaper.sh --apply <image>
  wallpaper.sh --current
  wallpaper.sh --previous
  wallpaper.sh --open-folder
  wallpaper.sh --theme-picker
  wallpaper.sh --theme-dynamic
  wallpaper.sh --theme-fallback
  wallpaper.sh --theme-status
  wallpaper.sh --online <osu|konachan|wallhaven-onepiece>
  wallpaper.sh --wallpaper-menu
  wallpaper.sh --generate-theme

Environment:
  MARCH_WALLPAPER_DIRS  Colon-separated wallpaper directories.
  MARCH_ONLINE_WALLPAPER_DIR  Directory for downloaded online wallpapers.
EOF
}

notify() {
    notify-send -t 3000 "march wallpaper" "$1" 2>/dev/null || printf '%s\n' "$1" >&2
}

notify_applied() {
    local image="$1"
    local accent="${2:-}"
    local message="Applied $(basename "$image")"

    if [[ -n "$accent" ]]; then
        message="$message\nAccent $accent"
    fi

    notify-send -t 3000 -i "$image" "march wallpaper" "$message" 2>/dev/null || printf '%b\n' "$message" >&2
}

current_image() {
    [[ -f "$current_wallpaper" ]] || return 1
    sed -n '1p' "$current_wallpaper"
}

ensure_dirs() {
    mkdir -p "$state_dir" "$generated_dir" "$repo_dir/wallpapers"

    if [[ ! -f "$rofi_colors" ]]; then
        printf '* {}\n' > "$rofi_colors"
    fi

    if [[ ! -f "$kitty_colors" ]]; then
        printf '# Generated by scripts/wallpaper.sh\n' > "$kitty_colors"
    fi
}

list_wallpapers() {
    IFS=':' read -r -a dirs <<< "$wallpaper_dirs"

    for dir in "${dirs[@]}"; do
        [[ -d "$dir" ]] || continue
        find "$dir" -type f \( \
            -iname '*.jpg' -o \
            -iname '*.jpeg' -o \
            -iname '*.png' -o \
            -iname '*.webp' -o \
            -iname '*.avif' -o \
            -iname '*.bmp' -o \
            -iname '*.gif' \
        \)
    done | sort -u
}

pick_wallpaper() {
    local selected

    selected="$(
        list_wallpapers | rofi -dmenu \
            -config "$palette_config" \
            -p "wallpaper" \
            -mesg "Local wallpapers from ./wallpapers and ~/Pictures/Wallpapers"
    )"

    [[ -n "$selected" ]] || exit 0
    apply_wallpaper "$selected"
}

random_wallpaper() {
    local selected

    selected="$(list_wallpapers | shuf -n 1)"
    if [[ -z "$selected" ]]; then
        notify "No local wallpapers found"
        exit 1
    fi

    apply_wallpaper "$selected"
}

show_current_wallpaper() {
    local image accent

    image="$(current_image || true)"
    if [[ -z "$image" || ! -f "$image" ]]; then
        notify "No current wallpaper"
        exit 1
    fi

    accent=""
    if [[ -f "$march_colors_json" ]] && command -v jq >/dev/null 2>&1; then
        accent="$(jq -r '.accent // empty' "$march_colors_json" 2>/dev/null || true)"
    fi

    notify_applied "$image" "$accent"
}

open_current_wallpaper_folder() {
    local image

    image="$(current_image || true)"
    if [[ -z "$image" || ! -f "$image" ]]; then
        notify "No current wallpaper"
        exit 1
    fi

    xdg-open "$(dirname "$image")" >/tmp/march-wallpaper-folder.log 2>&1 &
}

remember_wallpaper() {
    local image="$1"

    [[ -n "$image" && -f "$image" ]] || return 0
    {
        printf '%s\n' "$image"
        if [[ -f "$wallpaper_history" ]]; then
            grep -Fxv -- "$image" "$wallpaper_history" || true
        fi
    } | sed -n '1,20p' > "$wallpaper_history.tmp"
    mv "$wallpaper_history.tmp" "$wallpaper_history"
}

previous_wallpaper() {
    local previous current

    previous="$(sed -n '1p' "$wallpaper_history" 2>/dev/null || true)"
    if [[ -z "$previous" || ! -f "$previous" ]]; then
        notify "No previous wallpaper"
        exit 1
    fi

    current="$(current_image || true)"
    if [[ -n "$current" && -f "$current" && "$current" != "$previous" ]]; then
        {
            printf '%s\n' "$current"
            grep -Fxv -- "$previous" "$wallpaper_history" 2>/dev/null | grep -Fxv -- "$current" || true
        } | sed '/^$/d' | sed -n '1,20p' > "$wallpaper_history.tmp"
        mv "$wallpaper_history.tmp" "$wallpaper_history"
    else
        sed '1d' "$wallpaper_history" > "$wallpaper_history.tmp"
        mv "$wallpaper_history.tmp" "$wallpaper_history"
    fi

    apply_wallpaper "$previous" --no-history
}

theme_picker() {
    local selected

    selected="$(
        printf '%s\n' \
            "@ theme dynamic from wallpaper" \
            "@ theme fallback march glass" \
            "@ theme regenerate current" \
            "@ theme status" |
            rofi -dmenu \
                -config "$palette_config" \
                -p "theme" \
                -mesg "Dynamic uses matugen from current wallpaper. Fallback uses fixed march glass."
    )" || exit 0

    case "$selected" in
        "@ theme dynamic from wallpaper" | "@ theme regenerate current")
            enable_dynamic_theme
            ;;
        "@ theme fallback march glass")
            enable_fallback_theme
            ;;
        "@ theme status")
            theme_status
            ;;
    esac
}

wallpaper_menu() {
    local selected

    selected="$(
        printf '%s\n' \
            "local random" \
            "local picker" \
            "history previous" \
            "info current" \
            "info open folder" \
            "online osu seasonal" \
            "online konachan safe" \
            "online wallhaven onepiece" \
            "theme picker" \
            "theme status" |
            rofi -dmenu \
                -config "$palette_config" \
                -p "wall" \
                -mesg "local: files/random  history: previous  online: O/K/W  theme: colors"
    )" || exit 0

    case "$selected" in
        "local random")
            random_wallpaper
            ;;
        "local picker")
            pick_wallpaper
            ;;
        "history previous")
            previous_wallpaper
            ;;
        "info current")
            show_current_wallpaper
            ;;
        "info open folder")
            open_current_wallpaper_folder
            ;;
        "online osu seasonal")
            download_online_wallpaper osu
            ;;
        "online konachan safe")
            download_online_wallpaper konachan
            ;;
        "online wallhaven onepiece")
            download_online_wallpaper wallhaven-onepiece
            ;;
        "theme picker")
            theme_picker
            ;;
        "theme status")
            theme_status
            ;;
    esac
}

enable_dynamic_theme() {
    local image

    image="$(current_image || true)"
    if [[ -z "$image" || ! -f "$image" ]]; then
        notify "No current wallpaper to generate from"
        exit 1
    fi

    printf 'dynamic\n' > "$theme_mode"
    generate_palette "$image"
    notify "Dynamic theme generated from $(basename "$image")"
}

enable_fallback_theme() {
    printf 'fallback\n' > "$theme_mode"
    printf '{}\n' > "$march_colors_json"
    printf '* {}\n' > "$rofi_colors"
    printf '# Generated by scripts/wallpaper.sh\n' > "$kitty_colors"
    notify "Using fallback march glass theme"
}

theme_status() {
    local mode accent image

    mode="$(sed -n '1p' "$theme_mode" 2>/dev/null || printf 'dynamic')"
    image="$(current_image || true)"
    accent=""
    if [[ -f "$march_colors_json" ]] && command -v jq >/dev/null 2>&1; then
        accent="$(jq -r '.accent // empty' "$march_colors_json" 2>/dev/null || true)"
    fi

    notify "Mode: $mode
Wallpaper: ${image:+$(basename "$image")}
Accent: ${accent:-fallback}"
}

download_online_wallpaper() {
    local source="${1:-}"

    case "$source" in
        osu)
            download_osu_wallpaper
            ;;
        konachan)
            download_konachan_wallpaper
            ;;
        wallhaven-onepiece|wallhaven|onepiece)
            download_wallhaven_onepiece_wallpaper
            ;;
        *)
            notify "Unknown online source: ${source:-empty}"
            exit 2
            ;;
    esac
}

download_to_wallpapers() {
    local url="$1"
    local prefix="$2"
    local ext="${url%%\?*}"
    ext="${ext##*.}"

    case "$ext" in
        jpg|jpeg|png|webp|avif) ;;
        *) ext="jpg" ;;
    esac

    local save_dir file
    save_dir="$online_wallpaper_dir"
    mkdir -p "$save_dir"
    file="$save_dir/${prefix}_$(date +%Y%m%d_%H%M%S).$ext"

    curl -fL "$url" -o "$file"
    printf '%s\n' "$file"
}

download_osu_wallpaper() {
    require_online_tools

    local response count index url file
    response="$(curl -fsSL "https://osu.ppy.sh/api/v2/seasonal-backgrounds")"
    count="$(jq -r '.backgrounds | length' <<< "$response")"
    if [[ -z "$count" || "$count" == "0" ]]; then
        notify "osu returned no wallpapers"
        exit 1
    fi

    index=$((RANDOM % count))
    url="$(jq -r ".backgrounds[$index].url" <<< "$response")"
    file="$(download_to_wallpapers "$url" "osu_seasonal")"
    apply_wallpaper "$file"
}

download_konachan_wallpaper() {
    require_online_tools

    local page response url file
    page=$((1 + RANDOM % 1000))
    response="$(curl -fsSL "https://konachan.net/post.json?tags=rating%3Asafe&limit=1&page=$page")"
    url="$(jq -r '.[0].file_url // empty' <<< "$response")"
    if [[ -z "$url" ]]; then
        notify "Konachan returned no safe wallpaper"
        exit 1
    fi

    file="$(download_to_wallpapers "$url" "konachan_safe")"
    apply_wallpaper "$file"
}

download_wallhaven_onepiece_wallpaper() {
    require_online_tools

    local history page api json url file
    history="$state_dir/wallhaven-onepiece-history"
    touch "$history"

    page=$((RANDOM % 20 + 1))
    api="https://wallhaven.cc/api/v1/search?q=one%20piece&categories=010&purity=100&sorting=random&resolutions=1920x1080&ratios=16x9&page=$page"
    json="$(curl -fsSL "$api")"
    url="$(
        {
            jq -r '.data[].path' <<< "$json" |
                grep -vxFf "$history" |
                shuf -n 1
        } || true
    )"

    if [[ -z "$url" ]]; then
        url="$(jq -r '.data[].path' <<< "$json" | shuf -n 1)"
    fi

    if [[ -z "$url" ]]; then
        notify "Wallhaven returned no One Piece wallpaper"
        exit 1
    fi

    printf '%s\n' "$url" >> "$history"
    tail -n 200 "$history" > "$history.tmp"
    mv "$history.tmp" "$history"

    file="$(download_to_wallpapers "$url" "wallhaven_one_piece")"
    apply_wallpaper "$file"
}

require_online_tools() {
    local missing=()

    command -v curl >/dev/null 2>&1 || missing+=("curl")
    command -v jq >/dev/null 2>&1 || missing+=("jq")

    if (( ${#missing[@]} > 0 )); then
        notify "Missing required tools: ${missing[*]}"
        exit 1
    fi
}

generate_palette() {
    local image="$1"
    local matugen_tmp="$generated_dir/matugen.json.tmp"

    if ! command -v matugen >/dev/null 2>&1; then
        notify "Wallpaper applied. matugen is not installed, skipped colors."
        return 0
    fi

    if ! matugen image "$image" \
        --mode dark \
        --type scheme-tonal-spot \
        --source-color-index 0 \
        --json hex \
        > "$matugen_tmp" \
        2> "$generated_dir/matugen.log"; then
        rm -f "$matugen_tmp"
        notify "Wallpaper applied. matugen failed, skipped colors."
    else
        mv "$matugen_tmp" "$matugen_json"
        rm -f "$generated_dir/matugen.log"
        write_generated_palette
    fi
}

hex_to_rofi_rgba() {
    local hex="${1#"#"}"
    local alpha="$2"

    printf 'rgba(%d, %d, %d, %s%%)' \
        "0x${hex:0:2}" \
        "0x${hex:2:2}" \
        "0x${hex:4:2}" \
        "$alpha"
}

hex_to_qml_argb() {
    local hex="${1#"#"}"
    local alpha="$2"

    printf '#%s%s' "$alpha" "$hex"
}

write_generated_palette() {
    if [[ ! -f "$matugen_json" ]]; then
        notify "No matugen palette found yet"
        return 1
    fi

    if ! command -v jq >/dev/null 2>&1; then
        notify "Wallpaper applied. jq is not installed, skipped generated theme."
        return 0
    fi

    local bg bg_soft text text_muted text_dim accent accent2 accent3 error
    bg="$(jq -r '.colors.background.dark.color // "#0B0D12"' "$matugen_json")"
    bg_soft="$(jq -r '.colors.surface_container.dark.color // .colors.surface.dark.color // "#11141B"' "$matugen_json")"
    text="$(jq -r '.colors.on_surface.dark.color // "#F2F4F8"' "$matugen_json")"
    text_muted="$(jq -r '.colors.on_surface_variant.dark.color // "#A8B0C0"' "$matugen_json")"
    text_dim="$(jq -r '.colors.outline.dark.color // "#6F7787"' "$matugen_json")"
    accent="$(jq -r '.colors.primary.dark.color // "#8AADF4"' "$matugen_json")"
    accent2="$(jq -r '.colors.secondary.dark.color // "#C6A0F6"' "$matugen_json")"
    accent3="$(jq -r '.colors.tertiary.dark.color // "#91D7E3"' "$matugen_json")"
    error="$(jq -r '.colors.error.dark.color // "#ED8796"' "$matugen_json")"

    jq -n \
        --arg bg "$bg" \
        --arg bgSoft "$bg_soft" \
        --arg surface "$(hex_to_qml_argb "$bg_soft" "85")" \
        --arg surfaceStrong "$(hex_to_qml_argb "$bg_soft" "ad")" \
        --arg glassBg "$(hex_to_qml_argb "$bg" "75")" \
        --arg glassBorder "#24ffffff" \
        --arg glassHighlight "#38ffffff" \
        --arg glassShadow "#59000000" \
        --arg text "$text" \
        --arg textMuted "$text_muted" \
        --arg textDim "$text_dim" \
        --arg accent "$accent" \
        --arg accent2 "$accent2" \
        --arg accent3 "$accent3" \
        --arg success "$accent3" \
        --arg warning "$accent2" \
        --arg error "$error" \
        --arg barBg "$(hex_to_qml_argb "$bg" "94")" \
        --arg barBorder "#21ffffff" \
        --arg barActive "$(hex_to_qml_argb "$accent" "66")" \
        --arg barHover "#1affffff" \
        '{
            bg: $bg,
            bgSoft: $bgSoft,
            surface: $surface,
            surfaceStrong: $surfaceStrong,
            glassBg: $glassBg,
            glassBorder: $glassBorder,
            glassHighlight: $glassHighlight,
            glassShadow: $glassShadow,
            text: $text,
            textMuted: $textMuted,
            textDim: $textDim,
            accent: $accent,
            accent2: $accent2,
            accent3: $accent3,
            success: $success,
            warning: $warning,
            error: $error,
            barBg: $barBg,
            barBorder: $barBorder,
            barActive: $barActive,
            barHover: $barHover
        }' > "$march_colors_json"

    cat > "$rofi_colors" <<EOF
* {
    bg: $bg;
    surface: $(hex_to_rofi_rgba "$accent" 32);
    glass-bg: $(hex_to_rofi_rgba "$bg" 58);
    glass-border: rgba(255, 255, 255, 13%);
    glass-highlight: rgba(255, 255, 255, 18%);
    text: $text;
    text-muted: $text_muted;
    text-dim: $text_dim;
    accent: $accent;
    accent-2: $accent2;
}

window {
    background-color: $(hex_to_rofi_rgba "$bg" 78);
}

inputbar {
    background-color: rgba(255, 255, 255, 8%);
}

element selected {
    background-color: $(hex_to_rofi_rgba "$accent" 36);
}

button selected {
    background-color: $(hex_to_rofi_rgba "$accent2" 20);
}
EOF

    cat > "$kitty_colors" <<EOF
# Generated by scripts/wallpaper.sh

foreground $text
background $bg
selection_foreground $bg
selection_background $accent

cursor $accent
cursor_text_color $bg

url_color $accent3
active_border_color $accent
inactive_border_color $text_dim
bell_border_color $accent2
visual_bell_color $accent2

active_tab_foreground $bg
active_tab_background $accent
inactive_tab_foreground $text_muted
inactive_tab_background $bg_soft
tab_bar_background $bg

color0 $bg_soft
color1 $error
color2 #A6DA95
color3 #EED49F
color4 $accent
color5 $accent2
color6 $accent3
color7 $text

color8 $text_dim
color9 $error
color10 #A6DA95
color11 #EED49F
color12 $accent
color13 $accent2
color14 $accent3
color15 #FFFFFF
EOF
}

apply_wallpaper() {
    local image="$1"
    local mode="${2:-}"

    if [[ ! -f "$image" ]]; then
        notify "Wallpaper not found: $image"
        exit 1
    fi

    ensure_dirs

    local previous=""
    previous="$(current_image || true)"
    if [[ "$mode" != "--no-history" && -n "$previous" && "$previous" != "$image" ]]; then
        remember_wallpaper "$previous"
    fi

    printf '%s\n' "$image" > "$current_wallpaper"

    if command -v awww >/dev/null 2>&1; then
        awww img "$image" \
            --resize crop \
            --filter Lanczos3 \
            --transition-type grow \
            --transition-duration 0.8 \
            --transition-pos center \
            >/dev/null 2>&1 || true
    fi

    generate_palette "$image"
    local accent=""
    if [[ -f "$march_colors_json" ]] && command -v jq >/dev/null 2>&1; then
        accent="$(jq -r '.accent // empty' "$march_colors_json" 2>/dev/null || true)"
    fi
    notify_applied "$image" "$accent"
}

main() {
    ensure_dirs

    case "${1:-}" in
        --pick)
            pick_wallpaper
            ;;
        --random)
            random_wallpaper
            ;;
        --apply)
            [[ -n "${2:-}" ]] || {
                usage
                exit 2
            }
            apply_wallpaper "$2"
            ;;
        --current)
            show_current_wallpaper
            ;;
        --previous)
            previous_wallpaper
            ;;
        --open-folder)
            open_current_wallpaper_folder
            ;;
        --theme-picker)
            theme_picker
            ;;
        --theme-dynamic)
            enable_dynamic_theme
            ;;
        --theme-fallback)
            enable_fallback_theme
            ;;
        --theme-status)
            theme_status
            ;;
        --online)
            [[ -n "${2:-}" ]] || {
                usage
                exit 2
            }
            download_online_wallpaper "$2"
            ;;
        --wallpaper-menu)
            wallpaper_menu
            ;;
        --generate-theme)
            write_generated_palette
            ;;
        -h|--help|"")
            usage
            ;;
        *)
            usage
            exit 2
            ;;
    esac
}

main "$@"
